/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteRouteImport } from './routes/submit/route'
import { Route as ReviewRouteRouteImport } from './routes/review/route'
import { Route as EditorRouteRouteImport } from './routes/editor/route'
import { Route as ArticleRouteRouteImport } from './routes/article/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmitIndexRouteImport } from './routes/submit/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as ArticleIndexRouteImport } from './routes/article/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SubmitSubmissionIdRouteImport } from './routes/submit/$submissionId'
import { Route as ReviewSubmissionIdRouteImport } from './routes/review/$submissionId'
import { Route as EditorSubmissionIdRouteImport } from './routes/editor/$submissionId'
import { Route as ReviewAcceptTokenRouteImport } from './routes/review/accept/$token'

const SubmitRouteRoute = SubmitRouteRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRouteRoute = ReviewRouteRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRouteRoute = EditorRouteRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRouteRoute = ArticleRouteRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitIndexRoute = SubmitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubmitRouteRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRouteRoute,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRouteRoute,
} as any)
const ArticleIndexRoute = ArticleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticleRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SubmitSubmissionIdRoute = SubmitSubmissionIdRouteImport.update({
  id: '/$submissionId',
  path: '/$submissionId',
  getParentRoute: () => SubmitRouteRoute,
} as any)
const ReviewSubmissionIdRoute = ReviewSubmissionIdRouteImport.update({
  id: '/$submissionId',
  path: '/$submissionId',
  getParentRoute: () => ReviewRouteRoute,
} as any)
const EditorSubmissionIdRoute = EditorSubmissionIdRouteImport.update({
  id: '/$submissionId',
  path: '/$submissionId',
  getParentRoute: () => EditorRouteRoute,
} as any)
const ReviewAcceptTokenRoute = ReviewAcceptTokenRouteImport.update({
  id: '/accept/$token',
  path: '/accept/$token',
  getParentRoute: () => ReviewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/article': typeof ArticleRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/review': typeof ReviewRouteRouteWithChildren
  '/submit': typeof SubmitRouteRouteWithChildren
  '/editor/$submissionId': typeof EditorSubmissionIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/submit/$submissionId': typeof SubmitSubmissionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/article/': typeof ArticleIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/review/accept/$token': typeof ReviewAcceptTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$submissionId': typeof EditorSubmissionIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/submit/$submissionId': typeof SubmitSubmissionIdRoute
  '/admin': typeof AdminIndexRoute
  '/article': typeof ArticleIndexRoute
  '/editor': typeof EditorIndexRoute
  '/review': typeof ReviewIndexRoute
  '/submit': typeof SubmitIndexRoute
  '/review/accept/$token': typeof ReviewAcceptTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/article': typeof ArticleRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/review': typeof ReviewRouteRouteWithChildren
  '/submit': typeof SubmitRouteRouteWithChildren
  '/editor/$submissionId': typeof EditorSubmissionIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/submit/$submissionId': typeof SubmitSubmissionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/article/': typeof ArticleIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/review/accept/$token': typeof ReviewAcceptTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/article'
    | '/editor'
    | '/review'
    | '/submit'
    | '/editor/$submissionId'
    | '/review/$submissionId'
    | '/submit/$submissionId'
    | '/admin/'
    | '/article/'
    | '/editor/'
    | '/review/'
    | '/submit/'
    | '/review/accept/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor/$submissionId'
    | '/review/$submissionId'
    | '/submit/$submissionId'
    | '/admin'
    | '/article'
    | '/editor'
    | '/review'
    | '/submit'
    | '/review/accept/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/article'
    | '/editor'
    | '/review'
    | '/submit'
    | '/editor/$submissionId'
    | '/review/$submissionId'
    | '/submit/$submissionId'
    | '/admin/'
    | '/article/'
    | '/editor/'
    | '/review/'
    | '/submit/'
    | '/review/accept/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ArticleRouteRoute: typeof ArticleRouteRouteWithChildren
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
  ReviewRouteRoute: typeof ReviewRouteRouteWithChildren
  SubmitRouteRoute: typeof SubmitRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/': {
      id: '/submit/'
      path: '/'
      fullPath: '/submit/'
      preLoaderRoute: typeof SubmitIndexRouteImport
      parentRoute: typeof SubmitRouteRoute
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRouteRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/article/': {
      id: '/article/'
      path: '/'
      fullPath: '/article/'
      preLoaderRoute: typeof ArticleIndexRouteImport
      parentRoute: typeof ArticleRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/submit/$submissionId': {
      id: '/submit/$submissionId'
      path: '/$submissionId'
      fullPath: '/submit/$submissionId'
      preLoaderRoute: typeof SubmitSubmissionIdRouteImport
      parentRoute: typeof SubmitRouteRoute
    }
    '/review/$submissionId': {
      id: '/review/$submissionId'
      path: '/$submissionId'
      fullPath: '/review/$submissionId'
      preLoaderRoute: typeof ReviewSubmissionIdRouteImport
      parentRoute: typeof ReviewRouteRoute
    }
    '/editor/$submissionId': {
      id: '/editor/$submissionId'
      path: '/$submissionId'
      fullPath: '/editor/$submissionId'
      preLoaderRoute: typeof EditorSubmissionIdRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/review/accept/$token': {
      id: '/review/accept/$token'
      path: '/accept/$token'
      fullPath: '/review/accept/$token'
      preLoaderRoute: typeof ReviewAcceptTokenRouteImport
      parentRoute: typeof ReviewRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArticleRouteRouteChildren {
  ArticleIndexRoute: typeof ArticleIndexRoute
}

const ArticleRouteRouteChildren: ArticleRouteRouteChildren = {
  ArticleIndexRoute: ArticleIndexRoute,
}

const ArticleRouteRouteWithChildren = ArticleRouteRoute._addFileChildren(
  ArticleRouteRouteChildren,
)

interface EditorRouteRouteChildren {
  EditorSubmissionIdRoute: typeof EditorSubmissionIdRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorSubmissionIdRoute: EditorSubmissionIdRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

interface ReviewRouteRouteChildren {
  ReviewSubmissionIdRoute: typeof ReviewSubmissionIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ReviewAcceptTokenRoute: typeof ReviewAcceptTokenRoute
}

const ReviewRouteRouteChildren: ReviewRouteRouteChildren = {
  ReviewSubmissionIdRoute: ReviewSubmissionIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ReviewAcceptTokenRoute: ReviewAcceptTokenRoute,
}

const ReviewRouteRouteWithChildren = ReviewRouteRoute._addFileChildren(
  ReviewRouteRouteChildren,
)

interface SubmitRouteRouteChildren {
  SubmitSubmissionIdRoute: typeof SubmitSubmissionIdRoute
  SubmitIndexRoute: typeof SubmitIndexRoute
}

const SubmitRouteRouteChildren: SubmitRouteRouteChildren = {
  SubmitSubmissionIdRoute: SubmitSubmissionIdRoute,
  SubmitIndexRoute: SubmitIndexRoute,
}

const SubmitRouteRouteWithChildren = SubmitRouteRoute._addFileChildren(
  SubmitRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ArticleRouteRoute: ArticleRouteRouteWithChildren,
  EditorRouteRoute: EditorRouteRouteWithChildren,
  ReviewRouteRoute: ReviewRouteRouteWithChildren,
  SubmitRouteRoute: SubmitRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
